//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termoservis.Data.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.ContactInfo = new HashSet<ContactInfo>();
        }
    
        public int Id { get; set; }
        public string StreetLine { get; set; }
    
        public virtual ICollection<ContactInfo> ContactInfo { get; set; }
        public virtual Place Place { get; set; }
    }
}
