//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termoservis.Data.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commissioner : User
    {
        public Commissioner()
        {
            this.CustomerDevice = new HashSet<CustomerDevice>();
        }
    
    
        public virtual ICollection<CustomerDevice> CustomerDevice { get; set; }
    }
}
