//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termoservis.Data.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public ContactInfo()
        {
            this.Telephone = new HashSet<Telephone>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
    
        public virtual User User { get; set; }
        public virtual Address Address { get; set; }
        public virtual ICollection<Telephone> Telephone { get; set; }
    }
}
