//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termoservis.Data.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class County
    {
        public County()
        {
            this.Telephone = new HashSet<Telephone>();
            this.PostalOffice = new HashSet<PostalOffice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string CallCode { get; set; }
    
        public virtual ICollection<Telephone> Telephone { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<PostalOffice> PostalOffice { get; set; }
    }
}
