//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termoservis.Data.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDevice
    {
        public CustomerDevice()
        {
            this.Repair = new HashSet<Repair>();
            this.Service = new HashSet<Service>();
        }
    
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public bool IsObsolete { get; set; }
        public int Id { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Repair> Repair { get; set; }
        public virtual ICollection<Service> Service { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Commissioner Commissioner { get; set; }
        public virtual Device Device { get; set; }
    }
}
