//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termoservis.Data.Users
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsersDataModelContainer : DbContext
    {
        public UsersDataModelContainer()
            : base("name=UsersDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> UserSet { get; set; }
        public DbSet<Address> AddressSet { get; set; }
        public DbSet<ContactInfo> ContactInfoSet { get; set; }
        public DbSet<Telephone> TelephoneSet { get; set; }
        public DbSet<Country> CountrySet { get; set; }
        public DbSet<Place> PlaceSet { get; set; }
        public DbSet<PostalOffice> PostalOfficeSet { get; set; }
        public DbSet<CustomerDevice> CustomerDeviceSet { get; set; }
        public DbSet<Device> DeviceSet { get; set; }
        public DbSet<WorkItem> WorkItemSet { get; set; }
        public DbSet<JobRole> JobRoleSet { get; set; }
        public DbSet<County> CountySet { get; set; }
    }
}
