//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termoservis.Data.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItem
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
