//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termoservis.Data.Fiscalization
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEntity
    {
        public AccountEntity()
        {
            this.ItemEntities = new HashSet<ItemEntity>();
        }
    
        public int Id { get; set; }
        public string StoreName { get; set; }
        public string TreasuryName { get; set; }
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public int CancellationAccountNumber { get; set; }
        public Nullable<System.DateTime> CancellationAccountDate { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual ICollection<ItemEntity> ItemEntities { get; set; }
        public virtual CustomerEntity CustomerEntity { get; set; }
    }
}
