//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termoservis.Data.Fiscalization
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FiscalizationDataModelContainer : DbContext
    {
        public FiscalizationDataModelContainer()
            : base("name=FiscalizationDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ItemEntity> ItemEntitySet { get; set; }
        public DbSet<AccountEntity> AccountEntitySet { get; set; }
        public DbSet<CustomerEntity> CustomerEntitySet { get; set; }
    }
}
