//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termoservis.Data.Fiscalization
{
    using System;
    
    [Flags]
    public enum ItemTypes : int
    {
        NotSet = 0,
        Goods = 1,
        Service = 2
    }
}
