//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termoservis.Data.Fiscalization
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemEntity
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public ItemTypes Type { get; set; }
        public double Amount { get; set; }
        public double Price { get; set; }
        public double Discount { get; set; }
        public double DiscountAmount { get; set; }
        public double TotalPrice { get; set; }
        public double TotalPriceValue { get; set; }
    
        public virtual AccountEntity AccountEntity { get; set; }
    }
}
